# Copyright (c) 2024, WSO2 LLC. (http://www.wso2.com).
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License
################################################################################
openapi: 3.0.1
info:
  version: v0.1
  title: WSO2 API Manager - Governance
  description: |
    This document specifies a **RESTful API** for WSO2 **API Manager** - Governance.
  contact:
    name: WSO2
    url: http://wso2.com/products/api-manager/
    email: architecture@wso2.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://apis.wso2.com/api/am/governance/v0
tags:
  - name: Rules
    description: API for managing rules.
  - name: Governance Policies
    description: API for managing governance policies.
  - name: Governance Results
    description: API for accessing governance results.
  - name: Health Check
    description: API for health check.
  - name: Deprecated
    description: API resources that are deprecated.
paths:
  /rules:
    get:
      summary: Retrieves a list of rules.
      description: Returns a list of all rules associated with the requested organization.
      operationId: getRules
      tags:
        - Rules
      security:
        - OAuth2Security:
            - apim:gov_rule_read
    post:
      summary: Create a new rule.
      description: Creates a new rule in the user's organization.
      operationId: createRule
      tags:
        - Rules
      security:
        - OAuth2Security:
            - apim:gov_rule_manage
  /rules/{ruleId}:
    get:
      summary: Retrieves a rule by ID.
      description: Returns detailed information about a rule.
      operationId: getRuleById
      tags:
        - Rules
      security:
        - OAuth2Security:
            - apim:gov_rule_read
    put:
      summary: Update a rule by ID.
      description: Updates the details of a rule.
      operationId: updateRuleById
      tags:
        - Rules
      security:
        - OAuth2Security:
            - apim:gov_rule_manage
    delete:
      summary: Delete a rule by ID.
      description: Deletes a rule from the user's organization.
      operationId: deleteRuleById
      tags:
        - Rules
      security:
        - OAuth2Security:
            - apim:gov_rule_manage
  /rules/{ruleId}/usage:
    get:
      summary: Retrieves usage of each rule.
      description: Retrieves the list of policies which use the rule.
      operationId: getRuleUsage
      tags:
        - Rules
      security:
        - OAuth2Security:
            - apim:gov_rule_read

  /healthz/liveness:
    get:
      summary: Liveness Check
      description: Checks if the application is alive and able to respond to requests.
      operationId: getHealthzLiveness
      tags:
        - Health Check
  /healthz/readiness:
    get:
      summary: Readiness Check
      description: Checks if the application is ready to handle requests.
      operationId: getHealthzReadiness
      tags:
        - Health Check
  /governance-policies:
    get:
      summary: Retrieves a list of all governance policies.
      description: Retrieves a list of governance policies for the user's organization.
      operationId: getGovernancePolicies
      tags:
        - Governance Policies
      security:
        - OAuth2Security:
            - apim:gov_policy_read
    post:
      summary: Creates a new governance policy.
      description: Creates a new governance policy for the user's organization.
      operationId: createGovernancePolicy
      tags:
        - Governance Policies
      security:
        - OAuth2Security:
            - apim:gov_policy_manage
  /governance-policies/{policyId}:
    get:
      summary: Get a specific governance policy
      description: Retrieves details of a specific governance policy identified by the policyId.
      operationId: getGovernancePolicyById
      tags:
        - Governance Policies
      security:
        - OAuth2Security:
            - apim:gov_policy_read
    put:
      summary: Update a specific governance policy
      description: Updates the details of an existing governance policy identified by the policyId.
      operationId: updateGovernancePolicyById
      tags:
        - Governance Policies
      security:
        - OAuth2Security:
            - apim:gov_policy_manage
    delete:
      summary: Delete a specific governance policy
      description: Deletes an existing governance policy identified by the policyId.
      operationId: deleteGovernancePolicy
      tags:
        - Governance Policies
      security:
        - OAuth2Security:
            - apim:gov_policy_manage
  /artifact-governance-results:
    get:
      summary: Retrieves governance results of all artifacts
      description: Retrieves governance results of all artifacts in the organization.
      operationId: getGovernanceResultsForAllArtifacts
      tags:
        - Governance Results
      security:
        - OAuth2Security:
            - apim:gov_result_read
  /artifact-governance-results/{artifactId}:
    get:
      summary: Retrieve governance results for a specific artifact
      description: Retrieve governance results associated with a specific artifact including APIs within the organization using its unique ID.
      operationId: getGovernanceResultsByArtifactId
      tags:
        - Governance Results

      security:
        - OAuth2Security:
            - apim:gov_result_read
  /policy-governance-results:
    get:
      summary: Retrieve governance results for all policies
      description: Retrieve governance results of all governance policies within the organization.
      operationId: getGovernanceResultsForAllPolicies
      tags:
        - Governance Results
      security:
        - OAuth2Security:
            - apim:gov_result_read
  /policy-governance-results/{policyId}:
    get:
      summary: Retrieve governance results for a specific policy
      description: Retrieve governance results associated with a specific governance policy within the organization using its unique ID.
      operationId: getGovernanceResultsByPolicyId
      tags:
        - Governance Results

      security:
        - OAuth2Security:
            - apim:gov_result_read

components:
  securitySchemes:
    OAuth2Security:
      type: oauth2
      flows:
        password:
          tokenUrl: https://localhost:9443/oauth2/token
          scopes:
            openid: Authorize access to user details
            apim:gov_rule_read: Read governance rules
            apim:gov_rule_manage: Manage governance rules
            apim:gov_policy_read: Read governance policies
            apim:gov_policy_manage: Manage governance policies
            apim:gov_result_read: Read governance results