-- TABLE TO STORE THE RULES
CREATE TABLE IF NOT EXISTS GOV_RULE (
    RULE_ID VARCHAR(45) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(1024),
    APPLIES_TO VARCHAR(255) NOT NULL,
    SEVERITY VARCHAR(15),
    PROVIDER VARCHAR(255),
    ORGANIZATION VARCHAR(255) NOT NULL,
    CREATED_BY VARCHAR(255),
    CREATED_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(255),
    LAST_UPDATED_TIME DATETIME,
    CONSTRAINT RULE_UNIQUE_CONSTRAINT UNIQUE (NAME, ORGANIZATION),
    PRIMARY KEY (RULE_ID)
) ENGINE=INNODB;

-- TABLE TO STORE THE RULE FUNCTIONS
CREATE TABLE IF NOT EXISTS GOV_RULE_FUNCTION_MAPPING(
    RULE_FUNCTION_ID VARCHAR(45) NOT NULL,
    RULE_ID VARCHAR(45) NOT NULL,
    FUNCTION_NAME VARCHAR(255) NOT NULL,
    FUNCTION_PARAMETERS BLOB,
    FOREIGN KEY (RULE_ID) REFERENCES GOV_RULE(RULE_ID) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT RULE_FUNCTION_UNIQUE_CONSTRAINT UNIQUE (RULE_ID, FUNCTION_NAME),
    PRIMARY KEY (RULE_FUNCTION_ID)
) ENGINE=INNODB;

-- TABLE TO STORE THE RULE PATHS
CREATE TABLE IF NOT EXISTS GOV_RULE_PATH_MAPPING(
    RULE_PATH_ID VARCHAR(45) NOT NULL,
    RULE_ID VARCHAR(45) NOT NULL,
    PATH VARCHAR(255) NOT NULL,
    FOREIGN KEY (RULE_ID) REFERENCES GOV_RULE(RULE_ID) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT RULE_PATH_UNIQUE_CONSTRAINT UNIQUE (RULE_ID, PATH),
    PRIMARY KEY (RULE_PATH_ID)
) ENGINE=INNODB;

-- TABLE TO STORE THE POLICIES
CREATE TABLE IF NOT EXISTS GOV_POLICY (
   POLICY_ID VARCHAR(45) NOT NULL,
   NAME VARCHAR(255) NOT NULL,
   DESCRIPTION VARCHAR(1024),
   ACTION_ON_VIOLATION VARCHAR(255) NOT NULL,
   ORGANIZATION VARCHAR(255) NOT NULL,
   CREATED_BY VARCHAR(255),
   CREATED_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
   UPDATED_BY VARCHAR(255),
   LAST_UPDATED_TIME DATETIME,
   CONSTRAINT POLICY_UNIQUE_CONSTRAINT UNIQUE (NAME, ORGANIZATION),
   PRIMARY KEY (POLICY_ID)
) ENGINE=INNODB;

-- TABLE TO STORE THE POLICY LABELS
CREATE TABLE IF NOT EXISTS GOV_POLICY_LABEL (
    POLICY_LABEL_ID VARCHAR(45) NOT NULL,
    POLICY_ID VARCHAR(45) NOT NULL,
    LABEL VARCHAR(255) NOT NULL,
    FOREIGN KEY (POLICY_ID) REFERENCES GOV_POLICY(POLICY_ID) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT POLICY_LABEL_UNIQUE_CONSTRAINT UNIQUE (POLICY_ID, LABEL),
    PRIMARY KEY (POLICY_LABEL_ID)
) ENGINE=INNODB;

-- TABLE TO STORE THE POLICY RULE MAPPINGS
CREATE TABLE IF NOT EXISTS GOV_POLICY_RULE_MAPPING (
    POLICY_RULE_MAPPING_ID VARCHAR(45) NOT NULL,
    POLICY_ID VARCHAR(45) NOT NULL,
    RULE_ID VARCHAR(45) NOT NULL,
    FOREIGN KEY (POLICY_ID) REFERENCES GOV_POLICY(POLICY_ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (RULE_ID) REFERENCES GOV_RULE(RULE_ID) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT POLICY_RULE_UNIQUE_CONSTRAINT UNIQUE (POLICY_ID, RULE_ID),
    PRIMARY KEY (POLICY_RULE_MAPPING_ID)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXIST GOV_POLICY_STATE_MAPPING (
    POLICY_STATE_MAPPING_ID VARCHAR(45) NOT NULL,
    POLICY_ID VARCHAR(45) NOT NULL,
    STATE VARCHAR(45) NOT NULL,
    FOREIGN KEY (POLICY_ID) REFERENCES GOV_POLICY(POLICY_ID) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT POLICY_STATE_UNIQUE_CONSTRAINT UNIQUE (POLICY_ID, STATE),
    PRIMARY KEY (POLICY_STATE_MAPPING_ID)
) ENGINE=INNODB;

-- TABLE TO STORE DETAILS ABOUT THE ARTIFACT
CREATE TABLE IF NOT EXISTS GOV_ARTIFACT_INFO(
    ARTIFACT_ID VARCHAR(45) NOT NULL,
    TYPE VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    VERSION VARCHAR(255) NOT NULL,
    OWNER VARCHAR(255),
    ORGANIZATION VARCHAR(255) NOT NULL,
    CONSTRAINT ARTIFACT_UNIQUE_CONSTRAINT UNIQUE (NAME, VERSION, ORGANIZATION),
    PRIMARY KEY (ARTIFACT_ID)
) ENGINE=INNODB;

-- TABLE TO STORE THE RESULTS OF THE RULES
CREATE TABLE IF NOT EXISTS GOV_RESULTS (
    RULE_ID VARCHAR(45) NOT NULL,
    ARTIFACT_ID VARCHAR(45) NOT NULL,
    STATUS VARCHAR(45) NOT NULL,
    MESSAGE VARCHAR(1024),
    PATHS VARCHAR(1024),
    FOREIGN KEY (RULE_ID) REFERENCES GOV_RULE(RULE_ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (ARTIFACT_ID) REFERENCES GOV_ARTIFACT_INFO(ARTIFACT_ID) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (RULE_ID, ARTIFACT_ID),
) ENGINE=INNODB;

-- TABLE TO STORE THE EVENTS
CREATE TABLE GOV_EVENTS (
    ARTIFACT_ID VARCHAR(45) PRIMARY KEY,
    STATUS VARCHAR(45) NOT NULL,
    ORGANIZATION VARCHAR(255) NOT NULL,
    EVENT_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PROCESSED_TIMESTAMP TIMESTAMP NULL,
    FOREIGN KEY (ARTIFACT_ID) REFERENCES GOV_ARTIFACT_INFO(ARTIFACT_ID) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (ARTIFACT_ID, STATUS)
);

